version: 2.1

executors:
  node-10:
    docker:
      - image: circleci/node:10
    environment:
      EXECUTOR_NAME: node-10
  node-12:
    docker:
      - image: circleci/node:12
    environment:
      EXECUTOR_NAME: node-12
  puppeteer:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      EXECUTOR_NAME: puppeteer
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          name: build12
          e: node-12
      - build:
          name: build10
          e: node-10
      - build:
          name: puppeteerEnv
          e: puppeteer
      - test-dev-tools:
          e: node-12
          requires:
            - build12
      - test-dev-tools:
          e: node-10
          requires:
            - build10
      - test-config:
          e: node-10
          requires:
            - build10
      - test-json-file:
          e: node-10
          requires:
            - build10
      - test-expo-cli:
          e: node-12
          requires:
            - build12
      - test-expo-cli:
          e: node-10
          requires:
            - build10
      - test-expo-codemod:
          e: node-10
          requires:
            - build10
      - test-webpack-config-unit:
          e: node-10
          requires:
            - build10
      - test-webpack-config-e2e:
          e: puppeteer
          requires:
            - puppeteerEnv
      - test-webpack-config-e2e-next-js:
          e: puppeteer
          requires:
            - puppeteerEnv
      - test-expo-schemer:
          e: node-10
          requires:
            - build10
      - test-expo-pwa:
          e: node-10
          requires:
            - build10
      - test-coverage:
          e: node-12
          requires:
            - build12
      - test-electron-adapter:
          e: node-10
          requires:
            - build10
      - test-plist:
          e: node-10
          requires:
            - build10
      - test-metro-config:
          e: node-10
          requires:
            - build10
      - test-metro-config:
          e: node-12
          requires:
            - build12
jobs:
  build:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli
    steps:
      - checkout
      - run:
          # https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/20
          name: Configure env
          command: |
            echo "$EXECUTOR_NAME" > /tmp/.executor_name
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-{{ checksum "/tmp/.executor_name" }}-{{ checksum "yarn.lock" }}-v2
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Bootstrap (Link) Internal Dependencies
          command: yarn bootstrap
      - persist_to_workspace:
          root: "~"
          paths:
            - expo-cli
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ checksum "/tmp/.executor_name" }}-{{ checksum "yarn.lock" }}-v2
          paths:
            - ~/.cache/yarn
  test-dev-tools:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/dev-tools
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-config:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/config
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-json-file:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/json-file
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-expo-cli:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/expo-cli
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-expo-codemod:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/expo-codemod
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-webpack-config-unit:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test:unit
  test-webpack-config-e2e:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Install test project dependencies
          command: cd e2e/basic && yarn; cd ../..
      - run: yarn test:e2e
  test-webpack-config-e2e-next-js:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Install test project dependencies
          command: cd e2e/nextjs && yarn; cd ../..
      - run: yarn test:e2e:nextjs
  test-expo-schemer:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/schemer
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-expo-pwa:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/pwa
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-coverage:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test-coverage
  test-electron-adapter:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/electron-adapter
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-plist:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/plist
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
  test-metro-config:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/metro-config
    steps:
      - attach_workspace:
          at: "~"
      - run: yarn test
