version: 2.1

executors:
  node-10:
    docker:
      - image: circleci/node:10
  node-12:
    docker:
      - image: circleci/node:12
  puppeteer:
    docker:
      - image: circleci/node:latest-browsers
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          name: build12
          e: node-12
      - build:
          name: build10
          e: node-10
      - build:
          name: puppeteerEnv
          e: puppeteer
      - test-dev-tools:
          e: node-12
          requires:
            - build12
      - test-dev-tools:
          e: node-10
          requires:
            - build10
      - test-json-file:
          e: node-12
          requires:
            - build12
      - test-json-file:
          e: node-10
          requires:
            - build10
      - test-expo-codemod:
          e: node-12
          requires:
            - build12
      - test-expo-codemod:
          e: node-10
          requires:
            - build10
      - test-webpack-config-unit:
          e: node-12
          requires:
            - build12
      - test-webpack-config-unit:
          e: node-10
          requires:
            - build10
      - test-webpack-config-e2e:
          e: puppeteer
          requires:
            - puppeteerEnv
jobs:
  build:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-{{ parameters.e }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Bootstrap (Link) Internal Dependencies
          command: yarn bootstrap
      - persist_to_workspace:
          root: '~'
          paths:
            - expo-cli
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ parameters.e }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test-dev-tools:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/dev-tools
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn test
  test-json-file:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/json-file
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn test
  test-expo-codemod:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/expo-codemod
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn test
  test-webpack-config-unit:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn test:unit
  test-webpack-config-e2e:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: '~'
      - run:
          name: Install test project dependencies
          command: cd tests/basic && yarn && cd ../nextjs && yarn && cd ../..
      - run: yarn test:e2e
