# Useful resource: https://github.com/actions/starter-workflows

name: Test Package

on:
  pull_request
  # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestpaths
  # More helpful: https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  # push:
  #   branches:
  #     # If this isn't defined then all PR tests will be run twice
  #     - master
  #   paths:
  #     - '*'
  #     - '!*.md'
  # pull_request:
  #   paths:
  #     - '*'
  #     - '!*.md'

jobs:
  test:
    strategy:
      matrix:
        package: [dev-tools, json-file, expo-codemod, webpack-config]
        # Run tests with all of these node versions/systems :]
        node-version: [10.x, 12.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    name: ${{ matrix.package }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
        env:
          CI: true
      - name: Test ${{ matrix.package }}
        run: cd packages/${{ matrix.package }} && "$GITHUB_WORKSPACE/scripts/module-scripts-check-packages.sh"
        env:
          CI: true
